### ISSUE TITLE
frontend doesn't work

### ISSUE THREAD

**Issue by doppioslash** [sebastiw/company-distel#5]
I need to kickstart it by doing `M-x company-complete` once, and then it works.
emacs 24.5.1 on Mac OS X 10.10.5.
`.emacs` at my [dotfiles repo](https://github.com/doppioslash/dotfiles).

**Comment by sebastiw** [comment]
Thank you! I got Distel to work again with some effort, looking at your .emacs. The frontend is unstable, as discussed in issue #4. I have begun refactor the code, but it might take a while.

**Comment by ps2931** [comment]
Hi doppioslash,

I got following error: Cannot open load file: no such file or directory, company-distel-frontend
I cannot find company-distel-frontend. Where it is?

**Comment by sebastiw** [comment]
Hi,
I updated the master branch a couple of weeks ago, remove "(require
'company-distel-frontend)" from your .emacs as it is not needed and does
not exist anymore.

Merry Christmas

**Comment by ps2931** [comment]
Thanks for the quick reply. It's working now after I removed company-distel-frontend from .emacs.

Marry Christmas to you too :)
